services:
  buildmart:
    image: postgres:15.15
    container_name: buildmart
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=build
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/home/devuser/app
    depends_on:
      - buildmart
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@buildmart/build
    command: [ "/bin/sh", "-c", "alembic upgrade head && uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload" ]

volumes:
  postgres_data:
